FROM ruby:2.7.2-alpine
SHELL ["/bin/ash", "-eo", "pipefail", "-c"]

WORKDIR /coffee-oma
ARG ENV_FILE
ENV PORT 3001

COPY Gemfile Gemfile.lock  ./

RUN echo "$ENV_FILE" | base64 -d >.env  \
    && apk  --no-cache add linux-headers\
                        libxml2-dev\
                        make\
                        gcc\
                        libc-dev\
                        nodejs\
                        tzdata\
                        mysql-client \
                        mysql-dev \
                        git \
                        less \
                        imagemagick \
                        yarn &&\
    apk add --virtual build-dependencies --no-cache build-base curl-dev &&\
    gem install bundler -v 2.2.14 &&\
    bundle install -j4 &&\
    apk del build-dependencies

COPY . .
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

EXPOSE 3001
ENTRYPOINT ["entrypoinst.sh"]
