name: Rails Rspec
on:
  push:
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose,yml

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DB_HOST: 127.0.0.1
      DB_POET: 3300
      ENV_FILE: ${{secrets.ENV_FILE}}
    services:
      database:
        image: postgres:14.1
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: root
          BIND_ADDRESS: 0.0.0.0
    steps:
      - uses: actions/checkout@v2
      - name: SET up Ruby 2.7.2
        uses: ruby/setup-ruby@v1.68.0
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          working-directory: ./backend
      - name: Decode env file
        run: echo $ENV_FILE | base64 -d > .env
        working-directory: ./backend
      - name: Setup Database
        run: |
          cp config/database.yml.ci config/database.yml
          ./bin/rails db:create
          ./bin/rails db:migrate
        working-directory: ./backend
      - name: run rubocop
        run: bundle exec rubocop
        working-directory: ./backend
      - name: migration
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
        working-directory: ./backend
      - name: run rspec
        run: bundle exec rspec
        working-directory: ./backend

